Component/header hero
lucas-pvg/cp-presenca-cursinho-frontend pull request #2
Opened 2024-05-26 19:09 UTC by VictorASantana

## Creating:
**Hero component:** 
![image](https://github.com/lucas-pvg/cp-presenca-cursinho-frontend/assets/80405995/1b0e81aa-db66-49d6-9f09-02a271d3a60f)
**Header component:**
![image](https://github.com/lucas-pvg/cp-presenca-cursinho-frontend/assets/80405995/69b4fce7-27c7-4581-945c-ed36a2d597f4)

![image](https://github.com/lucas-pvg/cp-presenca-cursinho-frontend/assets/80405995/3e6f0d64-1503-4bd5-96f1-5203d4d43fa6)

**Obs:**
> Profile access icon not created yet. Gonna create it on another branch.
> Dark mode funcionality not implemented yet.

2024-06-11 20:16 UTC, pedrohrodrig commented on src/components/header/header.tsx
> +export const Header = ({ to, variant, mode, ...props }: HeaderProps) => {
Pq não um props direto que nem tu fez no outro PR? Pergunta genuína

2024-06-17 18:57 UTC, lucas-pvg commented on src/components/header/header.tsx
> +export const Header = ({ to, variant, mode, ...props }: HeaderProps) => {
Vou aproveitar pra responder pq sim. Quando vc usa props direto vc tá aceitando literalmente qualquer coisa ser passada pro seu componente. N tô falando só de tipagem, tô falando de nome de atributo tb. Apesar de a gente estar usando typescript e a interface do props ali em cima meio que resolver esse problema, é meio q uma boa prática listar certinho cada props pra garantir que ele avise caso vc tente passar algo meio x, sabe? Also permite vc controlar um pouco melhor quais atributos seu componente recebe.

2024-06-17 19:00 UTC, lucas-pvg requested changes
Amigo só troca ali a branch pra develop antes e aí gg, pode dar merge

2024-06-17 21:18 UTC, lucas-pvg approved these changes

2024-06-17 21:19 UTC, merged