Cadastros e Logout
lucas-pvg/cp-presenca-cursinho-frontend pull request #44
Opened 2024-10-14 12:40 UTC by pedrohrodrig

# EU JURO QUE ESSE É O ÚLTIMO PR GRANDERRRR

## O que foi feito?
- Tela de cadastros (em carga e unitário)
- Componente DragAndDrop
- Inserção de icons
- Logout

## Principais arquivos
- src/components/card-menu/card.css
- src/components/drag-and-drop/DragAndDrop.css
- src/components/drag-and-drop/DragAndDrop.tsx
- src/components/header/header.tsx
- src/components/modal/batch-register/batch-register.css
- src/components/modal/batch-register/batch-register.tsx
- src/components/modal/manual-register.tsx
- src/pages/users-page/users-page.css
- src/pages/users-page/users-page.tsx
- src/services/axios/index.ts

2024-10-14 12:49 UTC, VictorASantana commented on src/App.tsx
> +            />
Achei que ja tivessemos superado os commits de lint k k k k k

2024-10-14 12:54 UTC, VictorASantana approved these changes

2024-10-14 12:54 UTC, VictorASantana commented on src/components/modal/batch-register/batch-register.tsx
> +    setFile(files[0]);
Existe alguma possibilidade do usuario selecionar mais de um arquivo? Se acontecer, levando em conta que seria algo indesejavel, existe algum feedback?

2024-10-14 12:54 UTC, VictorASantana commented on src/pages/users-page/users-page.tsx
> +              {/* TODO: arrumar componente para ficar na tela inteira */}
Esse todo ainda ta valendo?

2024-10-14 13:30 UTC, lucas-pvg commented on src/App.tsx
> +            />
Kkkkkk

2024-10-14 13:43 UTC, lucas-pvg requested changes

2024-10-14 13:43 UTC, lucas-pvg commented on src/App.tsx
> +            <Route path="" element={<HomePage />} />
Eu sei que já tava assim, mas eu aprendi que o certo do reactDOM qnd vc quer q um compnente renderize em cima de outro, que é o caso aqui, é você omitir o path e usar a prorpiedade `index`:
```suggestion
            <Route index element={<HomePage />} />
```

2024-10-14 13:43 UTC, lucas-pvg commented on src/App.tsx
>    );
Amigo depois dá um git rebase antes de mergear pq aqui já tava certo na develop e você tá sobrescrevendo os paths com os que estavam antes de eu arrumar.

2024-10-14 13:43 UTC, lucas-pvg commented on src/components/icon/icon.tsx
>    }
Mesma coisa, tá sobrescrevendo coisa que já tava certa, no caso as propriedades de id e onClick dos ícones. Se subir isso aqui vai quebrar um monte de tela da develop. Faz git rebase antes e corrige os conflitos

2024-10-21 03:22 UTC, pedrohrodrig commented
@lucas-pvg aprova aq gay

2024-10-21 17:09 UTC, lucas-pvg approved these changes

2024-10-21 19:04 UTC, lucas-pvg requested changes

2024-10-21 19:04 UTC, lucas-pvg commented on src/components/card-menu/card.css
> +  transition: transform 0.2s ease-in-out;
Percebi depois só mas aqui vc tá sobrescrevendo uma transição q eu tô usando, então se puder corrigir pq senão eu vou ter q literalmente reescrever as linhas q foram substituídas dnv.
```suggestion
  text-align: center;
  white-space: normal;
  word-wrap: break-word;

  transition:
    transform .2s ease-in-out,
    color .2s ease-in-out,
    background-color .2s ease-in-out;
```

2024-11-01 19:43 UTC, lucas-pvg approved these changes

2024-11-01 19:52 UTC, merged